# Generated by Django 6.0.2 on 2026-02-26 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('wide_body', 'Wide Body'), ('narrow_body', 'Narrow Body'), ('regional', 'Regional Jet'), ('turboprop', 'Turboprop')], max_length=20)),
                ('size_code', models.CharField(choices=[('A', 'Code A (< 15m)'), ('B', 'Code B (15–24m)'), ('C', 'Code C (24–36m)'), ('D', 'Code D (36–52m)'), ('E', 'Code E (52–65m)'), ('F', 'Code F (65–80m)')], max_length=1)),
                ('is_wide_body', models.BooleanField(default=False)),
                ('pax_capacity', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=2, unique=True)),
                ('icao_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_home_airline', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='CheckInCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.IntegerField(unique=True)),
                ('is_dedicated_home_airline', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['counter_number'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.CharField(max_length=5, unique=True)),
                ('has_boarding_bridge', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['gate_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_flight_number', models.CharField(blank=True, max_length=10)),
                ('departure_flight_number', models.CharField(blank=True, max_length=10)),
                ('operation_type', models.CharField(choices=[('turnaround', 'Turnaround (Arrival + Departure)'), ('arrival', 'Arrival Only'), ('departure', 'Departure Only')], default='turnaround', max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter')], max_length=10)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)])),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('days_of_operation', models.IntegerField(default=127)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('conflict', 'Conflict'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='core.aircrafttype')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='core.airline')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_requests', to='core.airport')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_requests', to='core.airport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_from', models.IntegerField()),
                ('counter_to', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_allocations', to='core.flightrequest')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GateAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_allocations', to='core.flightrequest')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.gate')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ParkingStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_number', models.CharField(max_length=5, unique=True)),
                ('apron', models.CharField(choices=[('apron1', 'Apron 1 (Main, Nose-in)'), ('apron1ext', 'Apron 1 Extended (Remote, Nose-out)')], max_length=20)),
                ('size_code', models.CharField(choices=[('A', 'Code A (< 15m)'), ('B', 'Code B (15–24m)'), ('C', 'Code C (24–36m)'), ('D', 'Code D (36–52m)'), ('E', 'Code E (52–65m)'), ('F', 'Code F (65–80m)')], max_length=1)),
                ('has_boarding_bridge', models.BooleanField(default=False)),
                ('boarding_bridge_number', models.IntegerField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_stands', to='core.parkingstand')),
            ],
            options={
                'ordering': ['stand_number'],
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='connected_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='core.parkingstand'),
        ),
        migrations.CreateModel(
            name='StandAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_allocations', to='core.flightrequest')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.parkingstand')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
