# Generated by Django 4.2.29 on 2026-03-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('airlines', models.ManyToManyField(related_name='handlers', to='core.airline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirlineStandPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_bridge', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_preferences', to='core.airline')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.airport')),
                ('preferred_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parkingstand')),
            ],
        ),
        migrations.CreateModel(
            name='AirlineGatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hard_block', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_preferences', to='core.airline')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.airport')),
                ('preferred_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gate')),
            ],
        ),
    ]
