# Generated by Django 4.2.29 on 2026-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groundhandler_airlinestandpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='ground_days',
            field=models.IntegerField(default=0),
        ),
    ]
