# Generated by Django 5.2.6 on 2026-04-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ground_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOperationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('is_expected', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_overrides', to='core.flightrequest')),
            ],
            options={
                'ordering': ['-operation_date', 'flight_request_id'],
                'unique_together': {('flight_request', 'operation_date')},
            },
        ),
    ]
